version: '3'
services:
    handballgg:
        build: .
        restart: always
        ports:
            - "3000:3000"
        environment:
            DATABASE_mongodb: ${DATABASE_MONGODB}
            JWT_SECRET: ${JWT_SECRET}
        networks:
            - handballgg-network
        depends_on:
            - mongodb
    mongodb:
        image: mongo:4
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
        networks:
            - handballgg-network
networks:
    handballgg-network:
