version: '3'
services:
    handballgg:
        build: .
        restart: always
        ports:
            - "3000:3000"
        environment:
            DATABASE_mongodb: mongodb://admin:admin@mongodb:27017/
            JWT_SECRET: UQAwzuiD666c7Jbph27449vFz8Mhis5
        networks:
            - handballgg-network
    mongodb:
        image: mongo:4
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
            MONGO_INITDB_DATABASE: HandBallGG
        networks:
            - handballgg-network
networks:
    handballgg-network:
